### ISSUE TITLE
진행 방식 토의

### ISSUE THREAD

**Issue by ehdtndla123** [SKSpringStudy/Toby-Spring-3.1#4]
스터디 진행 방식에 대한 토의하기.

**Comment by ehdtndla123** [comment]
## ⭐ 스터디 진행 방식
* 각자 이름으로 Directory 를 생성합니다.
* 각주 마다 해와야할 분량의 Directory를 생성합니다. ex) Chapter01
* 그 Directory에는 그 공부에 대한 코드가 있거나 readme로 정리 해놓은 것이 있습니다.
* 각자 그 분량에 대해 모든 공부를 하고, 자기가 발표할 부분은 더 자세히 하고 정리도 더 잘 해옵니다.
* 서로 배정받은 부분에 대해서 발표를 하고 서로 토의하고 종료합니다.
* 그 후 다음주 분량 설정을 합니다.

**Comment by kangCoder** [comment]
- 매 주 공부할 파트 정하기
- 본인 폴더에 파트 별로 개인적으로 정리 해놓기
- 본인이 발표할 부분은 더 자세하게 정리 해놓기
- 서로 발표를 하고 발표에 대해 토의한다
- 공부한 파트를 이용하여 본인의 레거시 코드를 리팩토링 했다면 어떻게 사용했고, 어떤 결과가 도출되었는지도 발표한다

**Comment by sejoon00** [comment]
1. 한번에 해서 마지막 날에 올리는게 아니라 매일 일정량의 공부를 해서 올리는 시스템이었으면 좋겠음 ex) 월요일 : 1.1~ 1.2장  수요일:1.3~1.5장
2. 각자 공부하면서 공부한 내용에서 궁금한 것+ 에러난 내용이 있으면 반드시 그 내용을 정리해서 올려놓았으면 좋겠음
3. 스터디때 서로에게 물어보고 토의할 질문을 하나씩 정해오면 좋겠음

**Comment by sejoon00** [comment]
# 💡 스프링 스터디 진행방식 💡
- 각자 이름으로 Directory 를 생성합니다.
- 각주 마다 해와야할 분량의 Directory를 생성합니다. ex) Chapter01
- 그 Directory에는 그 공부에 대한 코드가 있거나 readme로 정리 해놓은 것이 있습니다.
- 각자 그 분량에 대해 모든 공부를 하고, 자기가 발표할 부분은 더 자세히 하고 정리도 더 잘 해옵니다.
    - 한번에 해서 마지막 날에 올리는게 아니라 매일 일정량의 공부를 해서 올립니다
        
        ex) 월요일 : 1.1~ 1.2장 수요일:1.3~1.5장
        
    - 각자 공부하면서 공부한 내용에서 궁금한 것+ 에러난 내용이 있으면 반드시 그 내용을 정리해서 올려놓습니다
    - 스터디때 서로에게 물어보고 토의할 질문을 하나씩 정해옵니다.
- 서로 배정받은 부분에 대해서 발표를 하고 서로 토의하고 종료합니다.
- 그 후 다음주 분량 설정을 합니다.
